version: '3'

services:
  db:
    image: mongo:5
    container_name: mongo-copa-libertadores
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: 'copa-libertadores'
    volumes:
      - ./mongo:/data/db